version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: fox
            MYSQL_PASSWORD: Douglas3
            MYSQL_DATABASE: livraria
            MYSQL_RANDOM_ROOT_PASSWORD: true
        ports:
            - "3306:3306"
        volumes:
            - /path/on/host:/var/lib/mysql
